### ISSUE TITLE
Permissions are never requested for iOS 6.

### ISSUE THREAD

**Issue by stevemckenzie** [heardrwt/RHAddressBook#1]
Solution here: https://devforums.apple.com/message/708024#708024

**Comment by heardrwt** [comment]
Is this a Beta 3 bug? 
Should the framework ask for system addressbook permission on behalf of the client?
Or should we just provide a wrapper for   ABAddressBookRequestAccessWithCompletion(addressBookRef, ^(bool granted, CFErrorRef error) ;

---

ABAddressBookRef addressBookRef = ABAddressBookCreateWithOptions(NULL, NULL);
if (ABAddressBookGetAuthorizationStatus() == kABAuthorizationStatusNotDetermined) {
  ABAddressBookRequestAccessWithCompletion(addressBookRef, ^(bool granted, CFErrorRef error) {
    // Do whatever you need.
  });
}

**Comment by stevemckenzie** [comment]
Yes its a change in beta 3. You now have to request permissions yourself.

**Comment by stevemckenzie** [comment]
Details about this are in the iOS 6 release notes under Address Book.

https://developer.apple.com/library/prerelease/ios/#releasenotes/General/RN-iOSSDK-6_0/_index.html#//apple_ref/doc/uid/TP40012166

**Comment by heardrwt** [comment]
This is fixed as of a5d1372f9b6ff18f442d2e6f5d464c99d93ed889
