### ISSUE TITLE
Submit to CocoaPods

### ISSUE THREAD

**Issue by seansu4you87** [heardrwt/RHAddressBook#10]
Hey there,

I've been using RHAddressBook for one of my projects and it's been working great!  Would you mind submitting it to [Cocoapods](http://cocoapods.org/), or if you want, I'll go ahead and submit it for you.

Thanks

**Comment by heardrwt** [comment]
something like this? https://gist.github.com/1ed602417c7d3b9daa96

**Comment by seansu4you87** [comment]
awesome!  thanks a lot!

**Comment by heardrwt** [comment]
https://github.com/CocoaPods/Specs/issues/769
