### ISSUE TITLE
iOS6: adressbook access not granted problem

### ISSUE THREAD

**Issue by ahmedadwani** [heardrwt/RHAddressBook#11]
If the access to contact is not activated in settings:
we have this error:
[RHAddressBookSharedServices init]:125 Error: Failed to create RHAddressBookSharedServices instance. Underlying ABAddressBookCreateWithOptions() failed with error: Error Domain=ABAddressBookErrorDomain Code=1 "The operation couldn’t be completed. (ABAddressBookErrorDomain error 1.)" 

and then, the application is blocked in that code (see the '---->' mark):
-(void)deregisterForAddressBookChanges{
        if (![[NSThread currentThread] isEqual:_addressBookThread]){
           ----> [self performSelector:_cmd onThread:_addressBookThread withObject:nil waitUntilDone:YES];
            return;
        }
    ....

This because _addressBookThread is Nil.

to solve this problem, I have test if we are not in that situation, then the code will be

-(void)deregisterForAddressBookChanges{
    if(_addressBookThread != nil) {
        if (![[NSThread currentThread] isEqual:_addressBookThread]){
            [self performSelector:_cmd onThread:_addressBookThread withObject:nil waitUntilDone:YES];
            return;
        }
    } else {
        return;
    }

If you have other solution, I am taker...

Thanks!

**Comment by heardrwt** [comment]
Ah, i assume you are compiling with ARC enabled. If its not enabled retain count is overridden so dealloc would never actually be called. 

I'll fix both of these issues up in my next commit.

**Comment by heardrwt** [comment]
I just pushed 3bde3c1adec148c687c341163b9f951c69c616f4 to resolve this issue.

**Comment by ahmedadwani** [comment]
Thank you!
