### ISSUE TITLE
Why RHAddressBookExternalChangeNotification is received when change the addressBook internally

### ISSUE THREAD

**Issue by flypigz** [heardrwt/RHAddressBook#12]
I think this is a question more than an issue. Any one know about this?

In my app, I try to monitor the RHAddressBookExternalChangeNotification, and reload my contacts data feeds when received the notification.

But when I change the contact profile internally, and invoke the RHAddressBook save method, then I got 1~3 RHAddressBookExternalChangeNotification, I don't understand this.

Does RHAddressBookExternalChangeNotification means the address book is changed by external applications? Not the current app......

Thanks.

**Comment by heardrwt** [comment]
The notification is fired both when you change stuff in your app and if someone else changes stuff externally. This means that every time you call save on an RHAddressBook Instance you will get a notification. This allows for you to have multiple separate RHAddressBook instances doing different things, that can be kept in sync. ie no changes? then we call revert to get latest changes.

A side effect of this is that you will get the notification, even if you are the one calling save.

**Comment by flypigz** [comment]
This is will let the app refresh its contacts data frequently, it is a waste of time. But I need to monitor the external changes.
What can I do? 
1. Every app needs to monitor the external changes, e.g. bring the app from background to foreground
2. Many app have a single address book instance, in this way we can ignore this internal changes totally
3. Supposed there is an app which has three address book instances. When one instance changed and saved, then all these three instances are notified and post a notification? then how many notifications we actually get? I guess is three? In this way, we are no way to design an multiple-thread app, because we needs to refresh frequently.... 

Correct me if am wrong.  Thanks.

**Comment by flypigz** [comment]
I look at the source codes. Can I comment below lines to avoid internal messages in my project? So we won't monitor the internal changes, for internal changes, I think we may need another internal change notification message, which will be posted when invoked the RHAddressBook/RHPerson/RHGroup save methods.

-(void)registerForAddressBookChanges{
//    if (![[NSThread currentThread] isEqual:_addressBookThread]){
//        [self performSelector:_cmd onThread:_addressBookThread withObject:nil waitUntilDone:YES];
//        return;
//    }

```
ABAddressBookRegisterExternalChangeCallback(_addressBook, RHAddressBookExternalChangeCallback, (__bridge void *)(self)); //use the context as a pointer to self
```

}

-(void)deregisterForAddressBookChanges{
//    if (_addressBookThread && ![[NSThread currentThread] isEqual:_addressBookThread]){
//        [self performSelector:_cmd onThread:_addressBookThread withObject:nil waitUntilDone:YES];
//        return;
//    }

```
// when unregistering a callback both the callback and the context
// need to match the ones that were registered.
if (_addressBook){
    ABAddressBookUnregisterExternalChangeCallback(_addressBook,  RHAddressBookExternalChangeCallback, (__bridge void *)(self));
}
```

}

**Comment by heardrwt** [comment]
I dont think commenting out this stuff will do what you want. That code is just making sure the calls happen on the internal addressbook thread. 

If you don't want to get any notifications at all, you can comment out [self registerForAddressBookChanges];, however you more than likely do want these notifications. Without them, during the lifetime of your app, you will never get any addressbook changes. 

eg: i add a new person in the contacts app and then switch back to your app, with the notifications disabled my new contact wont ever be visible in your app.

As an aside, the notifications are fairly light-weight. I wouldn't worry about them happening too often.

**Comment by flypigz** [comment]
YES, I got these:
1. all app need this notification, as your example above
2. This notification will be sent for all internal changes, and we don't know if this is for internal or external changes
3. sometimes, this notification will be broadcasted for multiple times for one save (my testing result)

Thanks for your help, Heardrwt!

**Comment by heardrwt** [comment]
I think that will work. However it might be simpler just to pretend the notifications don't exist.
Whenever you call save you can also call anything you need to do to refresh the UI.
