### ISSUE TITLE
RHMultiStringValue

### ISSUE THREAD

**Issue by Mpak87** [heardrwt/RHAddressBook#14]
Sir, could you advise please? I'm trying to create instance of RHMultiStringValue but it doesn't work. I did everything as procedure. In the same controller RHAddressBook is working person retrieved but... What can be the cause?

**Comment by heardrwt** [comment]
DO you happen to have a code example of what you are trying / what isnt working?

**Comment by heardrwt** [comment]
To create a new one you will need to create a Mutable MultiValue with type String. eg

RHMutableMultiStringValue *new = [RHMutableMultiValue alloc] initWithType:type]; where type is one of the below multi keys. 

<pre><code>
enum {
   kABInvalidPropertyType         = 0x0,
   kABStringPropertyType          = 0x1,
   kABIntegerPropertyType         = 0x2,
   kABRealPropertyType            = 0x3,
   kABDateTimePropertyType        = 0x4,
   kABDictionaryPropertyType      = 0x5,
   kABMultiStringPropertyType     = kABMultiValueMask | kABStringPropertyType
   kABMultiIntegerPropertyType    = kABMultiValueMask | kABIntegerPropertyType
   kABMultiRealPropertyType       = kABMultiValueMask | kABRealPropertyType
   kABMultiDateTimePropertyType   = kABMultiValueMask | kABDateTimePropertyType
   kABMultiDictionaryPropertyType = kABMultiValueMask | kABDictionaryPropertyType
};
RHMutableMultiStringValue *new = [RHMutableMultiValue alloc] initWithType:kABMultiStringPropertyType];
</code></pre>

**Comment by Mpak87** [comment]
The problem is seems to be in including static library to my project, but what is really unclear for me is why Xcode shows me when I type RH (in my implementation)  RHPerson, RHGroup, RHSource, RHRecord and RHAddress..., RHAuthorization. I've tried to put in RHAddressBook.h @class RHMultiString and then it show me in my imlementation file, but functionality isn't proper. And the other thing is when I typed RHMultiStringValue in my.m Xcode doesn't recognize (no highlight) but in quick inspector it show Declared in RHMultiValue.h
No idea why but try to play with pathes for headers.

**Comment by heardrwt** [comment]
Hopefully this can help.  http://rheard.com/blog/using-static-ios-libraries/

**Comment by Mpak87** [comment]
#import <RHAddressBook/AddressBook.h> 
I did mistake in this string. I'm so ashamed. I've put #import <RHAddressBook/RHAddressBook.h> that's why only partially static library was working. Sorry man for useless disturbing.

**Comment by Mpak87** [comment]
RHAddressBook/RHAddressbook.h instead of RHAddressBook/Addressbook.h

**Comment by heardrwt** [comment]
Ah, no worries. I'm certain i've made similar mistakes. It's not the most cleanly named set of files in the library.
