### ISSUE TITLE
Sources names

### ISSUE THREAD

**Issue by dvkch** [heardrwt/RHAddressBook#15]
Hi

I cannot find a way to have the name of a source, as it would appear in Contacts app, after calling group button. I expected something like "iCloud" or "Exchange (work)" etc but I cannot find a way to get these names.

So how can I get those names ?
And what is the "name" property of RHSource used for ?

Thanks

**Comment by heardrwt** [comment]
I don't believe there is a way to get the info the Contacts App displays. See http://stackoverflow.com/questions/4376738/iphone-address-book-list-sources-and-accounts

It might be worth filing a Radar on this if you feel it would be useful.

The name property returns the source name, as per ABAddressBook eg: 

<pre>
CFStringRef sourceName = (CFStringRef)ABRecordCopyValue(ABRecordGetRecordID(source, kABSourceNameProperty);
</pre>
