### ISSUE TITLE
Exception: -[NSThread rh_performBlock:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by bachand** [heardrwt/RHAddressBook#16]
I just added RHAddressBook to my iOS project using CocoaPods.  I imported the appropriate header file at the top of one of my ViewControllers:

```
#import <RHAddressBook/AddressBook.h>
```

Then, in `viewDidLoad`, I allocated and initialized an `RHAddressBook` instance:

```
RHAddressBook *ab = [[RHAddressBook alloc] init];
```

The app builds fine, but crashes on that line due to an uncaught exception.  Relevant console output:

```
-[RHAddressBookThreadMain threadMain:]:39 spawned thread: <NSThread: 0xa624c50>{name = RHAddressBookInstanceThread for instance 0xa6265e0, num = 5} 
-[NSThread rh_performBlock:]: unrecognized selector sent to instance 0xa61aef0
-[RHAddressBookThreadMain threadMain:]:39 spawned thread: <NSThread: 0xa61aef0>{name = RHAddressBookSharedServicesThread for 0xa624dd0, num = 6} 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSThread rh_performBlock:]: unrecognized selector sent to instance 0xa61aef0'
```

My project targets iOS 6 and is built with ARC enabled (though the RHAddressBook code itself is not built with ARC).

Stepping through the code, this exception is thrown the first time `rh_performBlock` is sent to an instance of `NSThread`.  It seems like the RHBlockAdditions category is not being properly added to the NSThread class...  Any ideas as to why this might be happening?

**Comment by heardrwt** [comment]
The category is not being loaded at runtime, likely due to it not being referenced in your app at link time, hence being excluded. 

Im not 100% familiar with how CocoaPods links code into your projects however i did come across this particular issue. https://github.com/CocoaPods/CocoaPods/issues/6

Perhaps make sure  '-ObjC -all_load' is set in linker flags for your project?

**Comment by bachand** [comment]
Yep, adding those linker flags to my project (not the CocoaPods project) fixed it.  [This](http://stackoverflow.com/questions/6820778/linking-objective-c-categories-in-a-static-library) StackOverflow thread was also helpful once I better understood the problem.

Thanks for the prompt response!

**Comment by heardrwt** [comment]
Glad to hear you worked it out. As an aside, i just set up a test project and included RHAddressBook using cocoapods and i didn't get the exception. 

By default my project had the -ObjC flag set, but not the -load_all. 
Perhaps all that is needed is -ObjC these days.

**Comment by bachand** [comment]
You're right, that works for me as well.  Thanks!  I updated the SO thread as well in case someone looks there.
