### ISSUE TITLE
Specify Public Headers in Podspec?

### ISSUE THREAD

**Issue by bachand** [heardrwt/RHAddressBook#17]
According to the CocoaPods documentation:

> If you do not explicitly set the list of public header files, all headers of source_files will be made public.
> s.public_header_files = 'Classes/*_/_.h'

In your XCode project, you specify 6 private headers:

RHAddressBookSharedServices.h
RHAddressBookGeoResult.h
NSThread+RHBlockAdditions.h
RHAddressBookThreadMain.h
RHAddressBook_Private.h
RHAddressBook/RHRecord_Private.h

Unless I'm missing something, it seems like the CocoaPods podspec should specify your public headers so that the above 6 headers are treated as private when CocoaPods builds RHAddressBook into its static library?

**Comment by heardrwt** [comment]
Ah, that sounds like a good idea. 

Do you know if their is an easy way to specify just the private headers? 
ie 

s.private_header_files = 'Classes/*_/__Private.h', 'RHAddressBookSharedServices.h', 'RHAddressBookGeoResult.h', 'NSThread+RHBlockAdditions.h', 'RHAddressBookThreadMain.h'

**Comment by bachand** [comment]
From my research, it doesn't seem like CocoaPods supports that by default.  You could do something like what they did in lines 4-33 of the Three20 podspec though:
https://github.com/CocoaPods/Specs/blob/master/Three20/1.0.11/Three20.podspec

May not be worth the extra code though...

**Comment by jstart** [comment]
Any update on making a podspec for this?

**Comment by heardrwt** [comment]
This project already has a podspec fyi. http://cocoapods.org/?q=rhaddressbook
