### ISSUE TITLE
Crash in [RHRecord performRecordAction:waitUntilDone:]_block_invoke_0

### ISSUE THREAD

**Issue by chitza** [heardrwt/RHAddressBook#18]
Hello,

I'm experiencing some unusual and inconsistent crashes when trying to access the thumbnail of an RHPerson object. I have about 6 crash reports, all with similar stack-traces.

I'm building against iOS SDK 6.0, the app is running on iOS 6.01 and is built with ARC, using the latest RHAddressBook code.

The stacktraces all look similar:

```
Exception Type:  SIGTRAP
Exception Codes: #0 at 0x39a5d68a
Crashed Thread:  4

Thread 0:
...
5   Fliple                              0x00063911 -[NSThread(RHBlockAdditions) rh_performBlock:waitUntilDone:] + 157
6   Fliple                              0x0005cc31 -[RHAddressBook performAddressBookAction:waitUntilDone:] + 121
7   Fliple                              0x00063b4b -[RHRecord performRecordAction:waitUntilDone:] + 127
8   Fliple                              0x00066e41 -[RHPerson imageWithFormat:] + 177
9   Fliple                              0x00066d77 -[RHPerson thumbnail] + 23
10  Fliple                              0x00022ac1 -[ctzDictionary tableView:cellForRowAtIndexPath:] (ctzDictionary.m:568) 
...

Thread 4 Crashed:
...
0   CoreFoundation                      0x39a5d68a _CFRelease + 18
1   Fliple                              0x00063b8d __46-[RHRecord performRecordAction:waitUntilDone:]_block_invoke_0 + 37
2   Fliple                              0x0005cc51 __56-[RHAddressBook performAddressBookAction:waitUntilDone:]_block_invoke_0 + 29
3   Fliple                              0x00063a49 -[NSThread(RHBlockAdditions) _rh_runBlock:] + 13
...
```

Most of the time the code runst just fine, except for some rare cases (that I couldn't reproduce so far), when it crashes.

My only suspicion is that the user has added/removed a contact source (such as Exchange/Facebook) and iOS is still adding/removing contacts in the background.
If this is the case, how could I protect my code against this kind of behavior?

**Comment by heardrwt** [comment]
I've just pushed a bunch of changes that guard against passing CF\* methods NULL's. Hopefully this will resolve these crashes you have been seeing.
