### ISSUE TITLE
Investigate adding gender to RHPerson.

### ISSUE THREAD

**Issue by heardrwt** [heardrwt/RHAddressBook#19]

**Comment by mortenhn1981** [comment]
Hi.

Im sorry for the confusion, it seems that the gender parameter was a misunderstanding between me and my co worker. He sent me a list of things he wanted to get from the addressbook and the list contained gender, i assumed that he knew it was there. Futher investergations showed that the addressbook do not contain gender.

Im very sorry for the misunderstanding, and again i want to thank you for developering RHAddressbook its a very cool wrapper and is very easy to use, it have already saved me tons of time.

happy hollidays.

Best Regards
Morten
