### ISSUE TITLE
Disable cache building as it takes a really really long ime and is not always necesary.

### ISSUE THREAD

**Issue by zebtin** [heardrwt/RHAddressBook#24]
I have found that on very large datasets the cache takes a really long time to build.

This is obvious as the addressbook tries to geocode every address, this might be ok if the plan is to use the data later.

But in case this data is not relevant I have not found a way to disable this functionality.

The rest of the framework works really well and its a pleasure to use, thank you for building it!

I will try to get around sending a pull request once I get the basic architecture of the framework down.

**Comment by heardrwt** [comment]
I actually pushed a commit last night that allows specifically for disabling all geo code at the preprocessor level. Check it out. https://github.com/heardrwt/RHAddressBook/commit/763a0ff5ae051e7c1feba8e49b703ac3e9376820

**Comment by zebtin** [comment]
Awesome! Tanks! I will pull right now!
