### ISSUE TITLE
Block execution until user grants authorisation to AddressBook

### ISSUE THREAD

**Issue by raelg** [heardrwt/RHAddressBook#25]
I'm trying to block program execution until the user grants access (or denies) access to the AddressBook, using  a semaphore, however this seems to block the entire UI thread. 
Using the code on http://stackoverflow.com/questions/12648244/programmatically-request-access-to-contacts-in-ios-6 

If the semaphore is omitted, the execution continues (effectively loading no data), until the App is closed and reopened. 

I have the following function:

``` objective-c
- (RHAddressBook *) addressBook {
    @synchronized (self) {
        if (_ab == nil) {
            _ab = [[RHAddressBook alloc] init];


            if ([RHAddressBook authorizationStatus] == RHAuthorizationStatusNotDetermined) {
                //request authorization
                dispatch_semaphore_t sema = dispatch_semaphore_create(0);
                [_ab requestAuthorizationWithCompletion:^(bool granted, NSError *error) {                
                    dispatch_semaphore_signal(sema);
                }];
                dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);
            }
        }
        return _ab;
    }
}
```

**Comment by heardrwt** [comment]
Try calling requestAuthorizationWithCompletion from the non main thread. 

My initiall guess is that requestAuthorizationWithCompletion is trying to run the block on the main thread, but the main thread is waiting for the semphore, so the block can never run.

**Comment by heardrwt** [comment]
The better option is to not block, but show the alert and then in the completion block call reload on your ViewController to populate the view. 

Until access is granted _ab will just return empty stuff.
