### ISSUE TITLE
Disable geocoding support without needing to edit RHAddressBook.h

### ISSUE THREAD

**Issue by airdrummingfool** [heardrwt/RHAddressBook#26]
Hello,
Is there a way to disable geocoding support without needing to edit RHAddressBook.h?

I tried wrapping `#define RH_AB_INCLUDE_GEOCODING 0` in an `#ifndef` and defining it in my prefix header, but the RHAddressBook library is built before my pch file is run, so I can't override it that way.

The reason I don't want to edit RHAddressBook.h is that I can't persist that change to the repo (and thus my other developers) unless I fork RHAddressBook.

Thanks,
Tommy

**Comment by heardrwt** [comment]
Good point. I should likely wrap my #define in an #ifndef.

```
#ifndef RH_AB_INCLUDE_GEOCODING
#define RH_AB_INCLUDE_GEOCODING 1
#endif
```

**Comment by airdrummingfool** [comment]
Yeah, I tried wrapping the #define in an #ifndef but that didn't work, I think because the library is built before my project is (and thus RHAddressBook.h's #ifndef would be evaluated before my #define in my prefix header).

**Comment by heardrwt** [comment]
I pushed commit 0f5b9e8a141fd2aa22e6e4c8eecab06542d06147
You might have better luck passing RH_AB_INCLUDE_GEOCODING=0 in Preprocessor Macros (GCC_PREPROCESSOR_DEFINITIONS).

**Comment by airdrummingfool** [comment]
I tried that too, but it did not work.

**Comment by heardrwt** [comment]
Are you including RHAB as a sub-project?

**Comment by airdrummingfool** [comment]
Yes, I followed the instructions at http://rheard.com/blog/using-static-ios-libraries/ to set it up.

**Comment by heardrwt** [comment]
This is the only reference i can find to being able to pass flags to sub-projects directly. 
ie using xcodebuild directly. 
http://www.cocoabuilder.com/archive/xcode/299246-can-pass-some-value-to-sub-project.html

**Comment by heardrwt** [comment]
Easiest option is likely forking.

**Comment by heardrwt** [comment]
But you could setup a run script phase to build the sub-project using xcodebuild with a custom configuration file that overrides GCC_PREPROCESSOR_DEFINITIONS to include RH_AB_INCLUDE_GEOCODING=0

**Comment by airdrummingfool** [comment]
Gotcha, thanks for looking into it!

**Comment by tonyxiao** [comment]
Shouldn't this be a run-time feature? Why use compile time macro for enabling / disabling?

**Comment by tonyxiao** [comment]
The main problem with current way of supporting geocoding is that it's super slow if there are a large number of contacts.
