### ISSUE TITLE
Better guidance for running with ARC?

### ISSUE THREAD

**Issue by idan** [heardrwt/RHAddressBook#28]
I'll preface this ticket with the fact that I'm a new iOS dev (coming from python/frontend tools-land).

I've built the static library, ensuring to set the relevant flags:

![screen shot 2013-05-16 at 5 25 17 pm](https://f.cloud.github.com/assets/22723/512930/9f9a6f34-be34-11e2-98c7-359b89200d31.png)

![screen shot 2013-05-16 at 5 26 51 pm](https://f.cloud.github.com/assets/22723/512935/adc9fa5c-be34-11e2-89f7-2be3538c7276.png)

Copied over the output and added it to my project:

![screen shot 2013-05-16 at 5 27 38 pm](https://f.cloud.github.com/assets/22723/512944/d49920f4-be34-11e2-8fa5-f25bd1f95235.png)

![screen shot 2013-05-16 at 5 28 27 pm](https://f.cloud.github.com/assets/22723/512949/ee96d51e-be34-11e2-9cde-85ecb0765ec2.png)

I have no trouble importing the .h file:

```
#import "RHAddressBook/AddressBook.h"
```

However as soon as I try to instantiate an RHAddressBook instance, my app crashes at runtime:

```
RHAddressBook *ab = [[RHAddressBook alloc] init];
```

causes:

```
2013-05-16 17:30:52.755 Braid[6970:4003] -[RHAddressBookThreadMain threadMain:]:39 spawned thread: <NSThread: 0x777ad00>{name = RHAddressBookSharedServicesThread for 0x777abb0, num = 4} 
2013-05-16 17:30:52.755 Braid[6970:370f] -[RHAddressBookThreadMain threadMain:]:39 spawned thread: <NSThread: 0x777a990>{name = RHAddressBookInstanceThread for instance 0x777a870, num = 3} 
2013-05-16 17:30:52.755 Braid[6970:c07] -[NSThread rh_performBlock:]: unrecognized selector sent to instance 0x777ad00
2013-05-16 17:30:52.768 Braid[6970:c07] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSThread rh_performBlock:]: unrecognized selector sent to instance 0x777ad00'
*** First throw call stack:
(0x1bfc012 0x1518e7e 0x1c874bd 0x1bebbbc 0x1beb94e 0x40fc1 0x40c54 0x34c8c 0x33bd 0x53e1c7 0x53e232 0x53e4da 0x5558e5 0x5559cb 0x555c76 0x555d71 0x55689b 0x5569b9 0x556a45 0x65c20b 0x4ad2dd 0x152c6b0 0x247fc0 0x23c33c 0x247eaf 0x54c2bd 0x494b56 0x49366f 0x493589 0x4927e4 0x49261e 0x4933d9 0x4962d2 0x54099c 0x48d574 0x48d76f 0x48d905 0x496917 0x2c9f 0x45a157 0x45a747 0x45b94b 0x46ccb5 0x46dbeb 0x45f698 0x1b57df9 0x1b57ad0 0x1b71bf5 0x1b71962 0x1ba2bb6 0x1ba1f44 0x1ba1e1b 0x45b17a 0x45cffc 0x299d 0x28c5)
libc++abi.dylib: terminate called throwing an exception
```

Any pointers to help me figure out what I'm doing incorrectly? Google and I have been best buddies for a couple of hours now, to no avail.

**Comment by chitza** [comment]
Excerpt from [the tutorial](http://rheard.com/blog/using-static-ios-libraries/):

"Make sure -all_load -ObjC is added to the Other Linker Flags section. (This makes sure everything in the static library is linked, even if not used at compile time. i.e. making it available at run time.)"

**Comment by heardrwt** [comment]
First off, it might be worth adding the framework as a sub-project as per the docs, it generally makes debugging etc later easier.

Secondly, my first guess would be along the same lines as chitza. The NSThread category is not being compiled into the static library. 
Make sure that the flags are set both in your project and in the static library when you are building it. I'm not sure from your screenshot if you have set the flag in your app, or for the library.

**Comment by idan** [comment]
@heardrwt @chitza ah, I think that did it—I was setting `-ObjC -all_load` on the library build, but not on the project where I was embedding it.

Thanks!
