### ISSUE TITLE
Cannot compile in Xcode 4.5 GM when ARC is enabled

### ISSUE THREAD

**Issue by nonamelive** [heardrwt/RHAddressBook#3]
Multiple error occurred when compiling with Xcode 4.5 GM when ARC is enabled.

Here are some errors:

/Volumes/Data HD/Users/Kai/Downloads/heardrwt-RHAddressBook-62338d9/RHAddressBook/RHAddressBook.m:187:5: Cast of block pointer type 'void (^)(bool, NSError *__strong)' to C pointer type 'const void *' requires a bridged cast
/Volumes/Data HD/Users/Kai/Downloads/heardrwt-RHAddressBook-62338d9/RHAddressBook/RHAddressBook.m:187:5: Cast of C pointer type 'void *' to block pointer type 'typeof (completion)' (aka 'void (^__strong)(bool, NSError *__strong)') requires a bridged cast
/Volumes/Data HD/Users/Kai/Downloads/heardrwt-RHAddressBook-62338d9/RHAddressBook/RHAddressBook.m:196:37: Cast of C pointer type 'CFErrorRef' (aka 'struct __CFError *') to Objective-C pointer type 'NSError *' requires a bridged cast
/Volumes/Data HD/Users/Kai/Downloads/heardrwt-RHAddressBook-62338d9/RHAddressBook/RHAddressBook.m:198:17: Cast of block pointer type 'void (^)(bool, NSError *__strong)' to C pointer type 'const void *' requires a bridged cast
/Volumes/Data HD/Users/Kai/Downloads/heardrwt-RHAddressBook-62338d9/RHAddressBook/RHAddressBook.m:211:9: Cast of block pointer type 'void (^)(bool, NSError *__strong)' to C pointer type 'const void *' requires a bridged cast

**Comment by heardrwt** [comment]
Thanks for reporting. This issue is resolved by 375e7ae.
