### ISSUE TITLE
Deprecations need fixing

### ISSUE THREAD

**Issue by rlaferla** [heardrwt/RHAddressBook#32]
RHAddressBook uses these two deprecated methods.  They need to be replaced.

ABAddressBookCreate() and ABPersonGetCompositeNameFormat()

**Comment by heardrwt** [comment]
Fixed by 0b3f86fc71465a3536a13a432f92c5905df16789 && 303c4ddeedd0f47a16bd812ee7c5f27ce1adb1e5

**Comment by rlaferla** [comment]
Great.  Has this been released in the CocoaPod?

**Comment by heardrwt** [comment]
As of now, yes. 1.0.4
