### ISSUE TITLE
Control geolocation inclusion/exclusion at runtime

### ISSUE THREAD

**Issue by nickbit** [heardrwt/RHAddressBook#38]
Hi Richard,
I am reopening my previous issue slightly different, since by using Cocoapods you cannot exclude geolocation by having a define in the projects .pch but a change in the RHAddressBook.h file is required. 
So if the project is updated one needs to change it again.
It would be more flexible to add geolocation at runtime instead.

**Comment by heardrwt** [comment]
From another issue, this is actually possible, however as of v1.1.0 geo is disabled by default.

```

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    if target.name == 'Pods-RHAddressBook'
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RH_AB_INCLUDE_GEOCODING=0'
      end
    end
  end
end
```
