### ISSUE TITLE
RHPerson::inSource confusing, source would be more logical

### ISSUE THREAD

**Issue by 0xdevalias** [heardrwt/RHAddressBook#39]
It took a while of searching around to figure out that `inSource` was the way to get the source. I think it would be more obvious if it was just `source`.

For backwards compatibility a convenience alias could be made of `source` calling back to `inSource` ?

**Comment by heardrwt** [comment]
I don't feel that inSource is particularly confusing for what it is. 

(Source -> contains -> Person ) 
(Person -> in -> Source)
