### ISSUE TITLE
RHPerson not being saved

### ISSUE THREAD

**Issue by johnryan** [heardrwt/RHAddressBook#40]
In some cases I find that contacts are not being saved when using code like this:

```
RHPerson *person = [self getPersonWithNumber:number];
RHMutableMultiStringValue* mutablePhoneMultiValue = [[RHMutableMultiStringValue alloc] initWithType:kABMultiStringPropertyType];

[mutablePhoneMultiValue addValue:number withLabel:details];
person.phoneNumbers = mutablePhoneMultiValue;
person.firstName = @"John Smith";
[person save];
```

The code is hit but it is not reflected in the address book. Any suggestions? Could it be a threading issue?

**Comment by heardrwt** [comment]
This is really going to depend on what your getPersonWithNumber: method looks like.

**Comment by johnryan** [comment]
Yea I saw this only a few times in the simulator but am not able to reproduce now. I'll close this, thanks!
