### ISSUE TITLE
Performance - rebuild cache

### ISSUE THREAD

**Issue by johnryan** [heardrwt/RHAddressBook#42]
With a large number of contacts, calling

[[RHAddressBook alloc] init]; 

can take a few minutes and block the main thread. It seems to be blocking on the rebuildCache method. Wrapping in a GCD async dispatch fixes the problem, but it still takes a few minutes before the address book is accessible. Is there anything I can do to speed up the cache rebuild?

**Comment by ryanfitz** [comment]
I ran into this same issue today. I found a workaround which is to set the macro RH_AB_INCLUDE_GEOCODING=0. This works as long as you don't need the geocoding functionality.

For anyone using cocoapods you can set this macro with the following change to your Podfile:

```

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    if target.name == 'Pods-RHAddressBook'
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RH_AB_INCLUDE_GEOCODING=0'
      end
    end
  end
end
```

**Comment by heardrwt** [comment]
This code is in need of a bit of love. Sorry for letting it slip. I've had other projects on the go for a little while now that have been keeping me busy!

**Comment by heardrwt** [comment]
I've pushed v1.1.0 to cocoapods that disabled geo by default and also switches to using GCD for thread safety. Full geo cleanup can happen some other time.

**Comment by johnryan** [comment]
what is the URL for the updated cocoapod? just using pod 'RHAddressBook' , '~> 1.1.0' throws an error?

Thanks!

**Comment by heardrwt** [comment]
Hey John, Seems that my push last night to CocoaPods failed due to access changes they have implemented. I have opened a pull request to get it into the mainline specs repo. https://github.com/CocoaPods/Specs/pull/8829

**Comment by johnryan** [comment]
Gotcha, looks all good now. Thanks.
