### ISSUE TITLE
Problems with flags in new release

### ISSUE THREAD

**Issue by ashvardanian** [heardrwt/RHAddressBook#43]
After updating to 1.1.0 problems with arc appeared. I do use a folder instead of packaging library to be able to make changes in source code. I have set the -all-load and -ObjC flags to "Other linker flags" and -fno-objc-arc to the files. Then tried different flags combinations but nothing worked for me. 
Even tried moving from arc_autorelease to cfrelease and other similar solutions. Do you have any ideas on what should I do to use your lib with ARC?

**Comment by heardrwt** [comment]
RHAddressBook natively supports building with ARC enabled. You should be able to just drop in the source files into your project and have it work.
