### ISSUE TITLE
Hanging in rh_performBlock: with XCode 5.1 and iOS 7.1

### ISSUE THREAD

**Issue by rlaferla** [heardrwt/RHAddressBook#46]
I'm seeing my app hang frequently on this code ever since upgrading to XCode 5.1 and iOS 7.1.  It happens when the app is installed on a device (more consistently for iPad Mini than iPhone 5s) but not in the simulator.

-(void)rh_performBlock:(VoidBlock)block waitUntilDone:(BOOL)wait{
    //if current thread and wait (run directly)
    if ([[NSThread currentThread] isEqual:self] && wait){
        block(); return;
    }
    [self performSelector:@selector(_rh_runBlock:) onThread:self withObject:arc_autorelease([block copy]) waitUntilDone:wait];
}

![image](https://f.cloud.github.com/assets/1135694/2450865/b6a596fa-aebf-11e3-892e-c14719edf688.png)

**Comment by heardrwt** [comment]
Hmmm, weird. that code does not exist in the latest version of the library. Feel free to update.

**Comment by rlaferla** [comment]
I'm using the CocoaPod: RHAddressBook (1.0.4).  Is there a newer CocoaPod?

**Comment by rlaferla** [comment]
Alas, I was not using 1.1.0!
