### ISSUE TITLE
dispatch_get_current_queue() deprecated in iOS 6.0

### ISSUE THREAD

**Issue by rlaferla** [heardrwt/RHAddressBook#47]
There's a compiler warning in RHAddressBook.m:

'dispatch_get_current_queue()' is deprecated: first deprecated in iOS 6.0

in the method rh_dispatch_is_current_queue_for_addressbook()

**Comment by heardrwt** [comment]
It's safe to ignore the warning because we only run that code-path on pre iOS 5 devices. 
I'll wrap it to suppress the warning.

**Comment by heardrwt** [comment]
e49b3f49e9e6ce67a614e199302ed31ef7083d25
