### ISSUE TITLE
Method for monitoring external address book changes

### ISSUE THREAD

**Issue by johnryan** [heardrwt/RHAddressBook#52]
I've noticed that the external changes notification is fired multiple times even when my app is the one manipulating the contacts. This sort of creates an infinite loop situation as my app modifies the contacts when they are changed (which then triggers a notification). I've also noticed that it often gets called multiple times when I do manipulate the contacts manually outside the app. I only have one RHAddressbook instance that I create. Is this a known issue?

Thanks a lot,
John

**Comment by heardrwt** [comment]
The notification is triggered directly by the ABAddressBook framework. We don't control when it's dispatched inside RHAddressBook. If you feel it's causing you issues it might be worth filing a Radar with Apple. It might also be worth setting a flag in your code, and keeping track of when you are making edits, so your logic wont re-enter the processing stage.

**Comment by johnryan** [comment]
Yep thats what i'm implementing now. Thanks for the quick update.
