### ISSUE TITLE
[RHPerson vCardRepresentationForPeople:] segfault

### ISSUE THREAD

**Issue by jhefner** [heardrwt/RHAddressBook#53]
After receiving address book authorization a call to 

```
[RHPerson vCardRepresentationForPeople:[addressBook people]]
```

results in a crash. Digging into the source it appears that while `vCardRepresentationForPeople`
expects an array of `RHPerson` objects, `ABPersonCreateVCardRepresentationWithPeople` expects a `CFArray` of `ABRecordRef` objects. Perhaps the `ABRecordRef` objects can be extracted from each `RHPerson` prior to the call to `ABPersonCreateVCardRepresentationWithPeople`.

**Comment by heardrwt** [comment]
Good catch. The -[RHAddressBook vCardRepresentationForPeople:]; method already does this correctly. I'm not a fan of the duplication of logic, so i'll make one method call into the other asap.

For now, use -[RHAddressBook vCardRepresentationForPeople:];

**Comment by jhefner** [comment]
Excellent. Thanks for fixing that so quickly.
