### ISSUE TITLE
RHAddressBookExternalChangeNotification fired multiple times

### ISSUE THREAD

**Issue by mrojas** [heardrwt/RHAddressBook#55]
I believe this is not a bug in RHAddressBook, but I thought I may ask here. I'm registering to listen for RHAddressBookExternalChangeNotification. I modify a contact in the native Contacts app, go back to my app and receive the notification as expected.
But a few seconds later, without taking any action in my app, I get 3 or 4 more callbacks.

It's actually RHAddressBookExternalChangeCallback that gets called by the iOS SDK, so this callbacks come from iOS itself.

I'm checking what has changed by iterating over the contacts and comparing the "modified" property.
So I go back to the app, get a notification and this is logged:

`2014-05-22 13:26:15.937 yyy[2584:3107] CONTACT XXXXXX modification date: 2014-05-22 12:26:11 +0000`

A few seconds later, I get another notification and this is logged:
`2014-05-22 13:26:23.763 yyy[2584:3107] CONTACT XXXXXX modification date: 2014-05-22 12:26:23 +0000`

The same contact seems to have been modified between the notifications, but my app is not doing that at all. In fact, it never writes to the address book.

Any ideas?

**Comment by heardrwt** [comment]
Yep, this is a known issue with ABAddressBook library. Not much we can really do about it, as we just send our notification from the ab changed callback.
