### ISSUE TITLE
[RHAddressBook people] does not retain objects in the array

### ISSUE THREAD

**Issue by euanlau** [heardrwt/RHAddressBook#7]
I am getting this error [RHPerson phoneNumbers]: message sent to deallocated instance intermittently. 
It all happens in a single function similar to this:

``` objective-c
NSArray *people = [addressBook people];
for (RHPerson *person in people)
{
   RHMultiValue *phoneNumbers = [person phoneNumbers];
}
```

It seems to me that the records are not retained properly.

I did spend time trying to identify the problem, but no luck.

BTW, I am using ARC and there is no internal/external change to the address book in my test.

**Comment by heardrwt** [comment]
I have been unable to reproduce the issue with ARC enabled and disabled. 
Do you have a reproducible test case?

Looking at the code directly everything looks to be in order.

**Comment by euanlau** [comment]
I need some time to reduce the test case. Thanks for looking into it.

**Comment by euanlau** [comment]
I have figured out what the problem was. I was accessing the same address book instance from more than one GCD queues. 
Thanks again for spending time on this!

**Comment by heardrwt** [comment]
Good to hear you worked it out.

**Comment by shenberg** [comment]
Why is accessing the same RHAddressBook from multiple threads a problem? Isn't the point of having RHAddressBookThreadMain letting you use the same instance from multiple threads?

**Comment by heardrwt** [comment]
The code should all be / is thread safe, i believe the threading issue that was reported above had more to do with application code not retaining an object correctly.

From the original complaint, calling a method on a deallocated object was throwing an NSZombies exception. ie messaging a deallocated object.

**Comment by shenberg** [comment]
Hey,
I'm getting the zombie errors on sending `[RHPerson release]` to zombies. I have an NSOperationQueue serving 40-50 concurrent operations where I commented out almost all the code, except for the line `NSArray *people = [rhAddressBook people];` (rhAddressBook is an RHAddressBook instance, of course).

I'm doing nothing else using the address book, yet somehow the objects get double-freed, and I don't really understand why. The code does look correct (except perhaps for atomicity and memory barriers, but I'm no expert in those matters.

More details: the project uses ARC, I wasn't sure whether 1.0.1 is significantly different than HEAD, so I tried both (same issue), and I also grew suspicious of USE_REF_MAP and USE_PERSON_ID_MAP so I disabled both (no luck there either). Also, when the crashes started it was in an app using RHAddressBook with ARC disabled as a pod, while the app had ARC enabled.

**Comment by heardrwt** [comment]
Could you isolate it to a simple test app so i can reproduce. Thanks. Also, perhaps open a new issue.

Also, be aware that the only thing holding a reference to a person from the returned array is the array. if you release the array, the RHPerson object will also be released. ARC, will helpfully do this releasing of the array for you.

**Comment by shenberg** [comment]
Done - it was surprisingly simple to get a working replication.
