### ISSUE TITLE
Compile issues with latest source

### ISSUE THREAD

**Issue by rlaferla** [heardrwt/RHAddressBook#70]
I am trying to incorporate the library directly instead of using CocoaPods but I'm seeing these new errors.  I don't see anything in the README that indicates any special compiler settings.  I suspect it's settings but it could be latest code.  How to resolve it?

RHAddressBookSharedServices.m:106:12: Implicit conversion of 'int' to 'RHAddressBookSharedServices *' is disallowed with ARC

RHAddressBookSharedServices.m:133:17: Implicit declaration of function 'arc_release_nil' is invalid in C99

**Comment by heardrwt** [comment]
Really you should add it as a subproject and then link it to your build as described in the docs.
I'm guessing you don't have your prefix header set to RHAddressBook-Prefix.pch. 
Either do that, or add its contents to your one.

**Comment by rlaferla** [comment]
Thanks, it was missing the pch.
