### ISSUE TITLE
Impressive feature set but slow

### ISSUE THREAD

**Issue by nickbit** [heardrwt/RHAddressBook#9]
I was impressed by the feature set provided by the library.
My old library (ABContactHelper by Erica Sadun) was replaced in half an hour.
But to my surprise, it was more than 2-3 times slower.

Can you take look at this?

**Comment by heardrwt** [comment]
Do you have any particular thoughts on what exactly is slower? 

There is obviously some overhead required to maintain the thread safety. We could likely switch over to using a dispatch queue instead of a thread at some point, now that ABAddressBook has clarified its thread safety model to include queues.

**Comment by nickbit** [comment]
I've done some time profile tests. May I sent you them?
It is the same app running both solutions.

**Comment by heardrwt** [comment]
Sure. email is richard at my domain

**Comment by nickbit** [comment]
Traces sent...

**Comment by heardrwt** [comment]
Sent over a .diff that replaces the AB internal Thread with a Queue.
http://pastebin.com/raw.php?i=5TiUMPYR

**Comment by heardrwt** [comment]
Nick, while simplifying the implementation of -(NSArray*)people; would be ideal, its not quite as simple as it appears on the surface. Most of the logic done in the people method is required to maintain thread safety. The good news is most of the performance hit is on the first access, so doing this on a background thread, async should be an easy solution for now. 

I'll be keeping an eye out for ways to dig into it and perhaps improve it further, however i wont have much time in the next 2 or so weeks.

If you need, i can offer some tips on the best ways to avoid blocking the main thread.

**Comment by nickbit** [comment]
Thank you Richard, I really appreciate your efforts. I want to use the code badly. It offers all the features I am seeking for.

As for the app, I am not blocking the main thread at the time, but since the app is Contacts based, the interface gets updated after processing the contacts.

What I realized while exploring your code is that the bottleneck (97%) is in the serial search for a matching RHPerson in the _people NSMutableSet, which is ever expanding.
A hash table lookup on another recordIDs cache could solve the problem.
Maybe a NSMutableDictionary linking recordIDs to RHPersons?
You know better of any implications.

Here is the offending code:

```
    //look in the cache
    for (RHPerson *entry in _people) {
        //compare using ID not ref
        if (personID == entry.recordID){
            person = arc_retain(entry);
            break;
        }
    }
```

**Comment by heardrwt** [comment]
Good catch. That can certainly be speed up. If i have some time tonight, i'll dig into it further. Thanks.

**Comment by heardrwt** [comment]
I just pushed a commit 642a8511faf8e384796c00d520e3f1d9f5e65648 that makes this stuff a bunch faster. 
Thanks for the feedback.

**Comment by nickbit** [comment]
Richard thank you very much.
You are amazing!
Nikos

Από το iPad μου

12 Νοε 2012, 4:27 π.μ., ο/η Richard Heard notifications@github.com έγραψε:
